### PR TITLE
Upgrade DB package to be version 1.9.3

### PR DESCRIPTION
**Pull request by seamuslee001**
This upgrades the version of the DB package to be 1.9.3 with our customisations on top

### CODE REVIEW

**Comment by seamuslee001** [comment]
These are our customisations ontop of the DB package https://gist.github.com/seamuslee001/18f00226850f3b3293d6ac54b205b286

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Tests pass & changes seem straight forward. Customisations look untouched. We've just cut the rc so a good time to merge

**Pull request merged**
