### PR TITLE
[REF] Additional PHP8.1 fix for passing in NULL value to strlen

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @demeritcowboy @totten @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
jenkins retest this please

**Pull request merged**
