### PR TITLE
dev/translation#50 Make recapture library locale aware

### PR DESCRIPTION
**Pull request by seamuslee001**
This picks up the patch from https://civicrm.stackexchange.com/questions/11533/recaptcha-update-language/37503 by @adixon 

@mattwire @mlutfy @MikeyMJCO

### CODE REVIEW

**Comment by adixon** [comment]
Thank for this. I wasn't convinced this is the right approach - including civi-specific code within a library seems wrong - but least we've now got a conversation. The right solution would be to update the upstream library upstream with a patch that included language in the library call as a parameter, and then include that getLocale call in the civi code that calls the library function. Or maybe there's already a better upstream version? Yeah, that's a whole new can of worms.

**Comment by MikeyMJCO** [comment]
It's the right can of worms imo. We should avoid patching third party libraries and opt for libraries that meet our needs or upstream patches.

**Comment by MikeyMJCO** [comment]
I'm not sure what library we're using but the official PHP lib is supported and language aware... https://github.com/google/ReCAPTCHA

**Comment by MikeyMJCO** [comment]
Definitely in favour of the effort going towards "modern recaptcha" library vs patch ancient unsupported library.

**Comment by adixon** [comment]
So, that leaves us with the work of trying to update the places in civi code that are using this newer version of the library and update the calls to what is almost certainly a more modern and complicated library ...

**Comment by MikeyMJCO** [comment]
Work we're going to have to do anyway eventually... either when PHP makes something in this 2007 code break or when Google turn off RECAPTHA v2. 

I'm going to look at what it would take to switch - the invocation of both is pretty similar and this would give us scope to introduce v3 support which has been requested.

**Comment by MikeyMJCO** [comment]
So the library I linked is more for server-side verification. There is no client side replacement, seems like we'd be better off dropping the library and moving the functions to generate recaptcha elements directly into core.

All the library seems to be doing is inserting the HTML for the recaptcha elements?

**Comment by seamuslee001** [comment]
@MikeyMJCO the library also does the post to run the validation I think as well but this pr will need to be redone once #317 is merged

**Comment by seamuslee001** [comment]
closing as this is now conflicted

**Pull request closed without merging**
