### PR TITLE
CRM-21059 Upgrade Smarty to 2.6.30

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-21059](https://issues.civicrm.org/jira/browse/CRM-21059)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
ping @jackrabbithanna

**Comment by seamuslee001** [comment]
jenkins, test this please

**Comment by jackrabbithanna** [comment]
Tested on my local, merging #195

**Pull request merged**
