### PR TITLE
Smarty4 -  updates to latest versions Smarty 4.51

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Note this does add some deprecation noise - which is mitigated by https://github.com/civicrm/civicrm-core/pull/29856

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this just pulls in the latest for both....

**Comment by eileenmcnaughton** [comment]
Ah - so this will help https://github.com/civicrm/civicrm-core/pull/29856

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
