### PR TITLE
[REF] Activate fetchAll function in DataObject file

### PR DESCRIPTION
**Pull request by seamuslee001**
This depends on https://github.com/civicrm/civicrm-core/pull/16198 to work

ping @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Error is

```
PHP Warning:  Declaration of CRM_Core_DAO::fetchAll() should be compatible with DB_DataObject::fetchAll($k = false, $v = false, $method = false) in /home/jenkins/bknix-dfl/build/pkg-281-4c2cn/web/sites/all/modules/civicrm/CRM/Core/DAO.php on line 33
PHP Stack trace:
PHP   1. {main}() /home/jenkins/bknix-dfl/build/pkg-281-4c2cn/web/sites/all/modules/civicrm/xml/GenCode.php:0
```
This PR https://github.com/civicrm/civicrm-core/pull/16198 fixes it

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton should this be considered MOP now?

**Comment by eileenmcnaughton** [comment]
yes

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
