### PR TITLE
Remove each() in favor of doing standard foreach as each is deprecated

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @totten @monishdeb

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I suppose there are no later releases of this package? - This is required for php 7.2?

**Comment by seamuslee001** [comment]
closing in favor of #205

**Pull request closed without merging**
