### PR TITLE
Remove Pear CLI from 4.6 as per PR #160 from Tim in master 

### PR DESCRIPTION
**Pull request by seamuslee001**
needs to be merged after https://github.com/civicrm/civicrm-core/pull/8817

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton This is a port of Tim cleaning up the PEAR stuff to remove PEAR cli. This has been merged into the master branch, we can wait but I would be interested in your thoughts on this

**Comment by JoeMurray** [comment]
@seamuslee001 have you a) done the scanning of the 4.6 codebase for calls into these libraries that @totten did for master? b) successfully run the full test suite on 4.6 after these commits?

**Comment by seamuslee001** [comment]
@JoeMurray did the greps and found it broke phpunit and reverted relevant commit. Am running the tests now locally and they look decent.

**Comment by eileenmcnaughton** [comment]
OK - I will merge this now as early in the 4.6 cycle & any issues are likely to show up when CI runs on it.

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you merge civicrm/civicrm-core#8817 as well please

**Pull request merged**
