### PR TITLE
[php8-compat] Fix calling method_exist with paremeter that is bool not an object in…

### PR DESCRIPTION
**Pull request by seamuslee001**
… php8

like https://github.com/civicrm/civicrm-core/pull/20443 this just adds a check to make sure that $result is actually a class object

ping @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
what else would it be? is this a flaw in the upstream code or in our usage/ hacks to this?

**Comment by seamuslee001** [comment]
@eileenmcnaughton it was complaining it was an integer iirc so maybe but it was pretty early on in the process so this resolves it at least

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Ok - I guess this particular function is already hacked so it might be our hack that is bad. I'm not keen on hacking packages but this just an extra check I guess

**Pull request merged**
