### PR TITLE
Fix typo in CIVICRM_MAIL_LOG_AND_SEND constants

### PR DESCRIPTION
**Pull request by mattwire**
https://lab.civicrm.org/dev/core/issues/86

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
per https://github.com/civicrm/civicrm-core/pull/12037 we should make this an OR (ie honour old & add new) not a replacement - happy to merge if you fix to that

**Comment by mattwire** [comment]
@eileenmcnaughton I've updated this to include the old define too.

**Comment by eileenmcnaughton** [comment]
OK that works

**Comment by mattwire** [comment]
@monishdeb @seamuslee001 Either of you able to merge this before 5.1.0 is released? As the other part is already merged into CiviCRM core - @eileenmcnaughton has given her approval I think

**Comment by seamuslee001** [comment]
Merging as per the label

**Comment by eileenmcnaughton** [comment]
Thanks both - note this is merged in time to hit the 5.2 rc not 5.1 (per the other)

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @xurizaemon you may have been annoyed by this messed up constant in the past & be pleased to see this

**Comment by xurizaemon** [comment]
Thankyou for knowing what's relevant to my pernickety interests

**Comment by eileenmcnaughton** [comment]
:-)

**Pull request merged**
