### PR TITLE
Remove the print_array modifier as it is now supplied in civicrm-core

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fail expected until https://github.com/civicrm/civicrm-core/pull/19206 is merged (note fail happens when running `./setup.sh -g`

**Comment by seamuslee001** [comment]
Added MOP based on @eileenmcnaughton being comfortable with the core PR

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by MegaphoneJon** [comment]
@seamuslee001 I have a great deal of appreciation for your years-long efforts to deprecate both this repo and the Civi-specific patches!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yes - so true

**Pull request merged**
