### PR TITLE
dev/core#2558 Insert blank MYSQLTIMESTAMP fields as NULL rather than 0

### PR DESCRIPTION
**Pull request by ufundo**
Extends the behaviour for date fields to timestamp fields also. This was hinted at in the comment but maybe there was a reason not to?

Seems to fix https://lab.civicrm.org/dev/core/-/issues/2558 for me, but is way out of my comfort zone!

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Cross-referencing: https://github.com/civicrm/civicrm-core/pull/20113

Jenkins test this please (I can't remember if tests run on civicrm-packages)

**Comment by demeritcowboy** [comment]
Jenkins add to whitelist ?

**Comment by seamuslee001** [comment]
@demeritcowboy do you want to try that last command again pls

**Comment by demeritcowboy** [comment]
Jenkins add to whitelist ?

**Comment by eileenmcnaughton** [comment]
tests failed - wonder why - definitely relates

**Comment by seamuslee001** [comment]
@eileenmcnaughton these are potentially flakey tests going to run it again just to be sure

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Looks like test fails were the second barrier issue rather than this PR

**Pull request merged**
