### PR TITLE
dev/drupal#169 - Fix namespacing in kcfinder

### PR DESCRIPTION
**Pull request by demeritcowboy**
Updates https://github.com/civicrm/civicrm-packages/pull/335 to avoid namespace issue.

### CODE REVIEW

**Comment by tapashdatta** [comment]
This works @demeritcowboy. Thanks

**Comment by colemanw** [comment]
Unrelated test fails.

**Comment by demeritcowboy** [comment]
Thanks. I'll put up a 5.45 backport in case there's a .1 release.

**Comment by totten** [comment]
On the explanation, "fix namespacing" is a little opaque. I searched a bit and added a link to Stackexchange, which seems to be the original error report.

So to clarify scope of impact... the original issue `dev/drupal#169` was about environmental-compatibility. Did this regression impact all environments or just some environments? Are we missing some coverage here (either wrt `r-run` or `phpunit`)?

**Comment by seamuslee001** [comment]
@totten it only affected Drupal 8./9 AFAIK as that is the only one where the namespacing is important.

**Comment by demeritcowboy** [comment]
Yes it should just be drupal 8/9.

I'd say the coverage gap on 335 was mostly a review fail, but with a partial excuse. I tested it on drupal 7 and tried to test it on drupal 8 but kcfinder didn't work on drupal 8 so I didn't think too much more about it. Or at least it doesn't work out of the box - obviously some people have a workaround.

And for the description here I should have linked directly to [the comment](https://github.com/civicrm/civicrm-packages/pull/335#commitcomment-63171960) on 335. And yes it's only partly related to dev/drupal169 - 335 was something @seamuslee001 put up as a followup to the fix for dev/drupal169 for completeness.

**Comment by totten** [comment]
Yeah, the disposition of ckeditor/kcfinder/cms-compat is confusing. And testing something like this is... rather persnickity...

FWIW, the report on StackExchange had some D7 indicators (`sites/all/modules` is more common D7), and I was perplexed by the idea that  `civicrm-packages/kcfinder/core/class/browser.php` has different namespacing based on CMS revision. So I retested on D7 - for me, (a) the error arises on D7 and (b) the patch solves it on D7. 👍  

(So in the RN's, I omitted any qualifier about CMS/environment.)

**Comment by demeritcowboy** [comment]
Interesting. I just tried again with my local drupal 7 and it's fine without the backslash. Maybe some other factor? Anyway it seems fixed for everybody now.

Trying to think if I can blame something on composer...

**Pull request merged**
