### PR TITLE
XML_RPC, PEAR DB Drivers - Remove unused dependencies

### PR DESCRIPTION
**Pull request by totten**

### CODE REVIEW

**Comment by mfb** [comment]
jenkins, test this please

**Comment by mfb** [comment]
This looks good to me. 

I guess there is no way to run automated tests/builds on PRs for this repo?

**Comment by colemanw** [comment]
There might be a way to do that. @totten ?

**Comment by totten** [comment]
@mfb @colemanw , I'd love to run the automated tests on all the repos.

At the moment, the test script used for PRs in `civicrm-core.git` has grown a little verbose/unruly, so I don't want to just copy-paste the job. What I'd like to do is extract a script which can "run all tests"; then the Jenkins job is smaller/more maintainable. Then it would be OK to copy-paste the small job. (It also makes it easier to run manually or in different/future CI's.)

Compare the current and wishlist versions of the test script: https://gist.github.com/totten/6752d04bba95a99f88945e2e888c0cd8

**Pull request merged**
