### PR TITLE
Upgrade DB_Dataobject package to the latest version 

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
We have a load of patches on this repo - it's pretty hard to see how they have been resolved - what process did you use?

**Comment by eileenmcnaughton** [comment]
Here is the list of patches (since svn) I found

4483923c CRM-20455 - DB_common::modifyQuery() - Optimize
7c3733b9 Improve deadlock error handling
3df0ba15  CRM-20445 Add query dispatcher to allow query modification.
6ce43856 Change the connection and results charsets to utf8mb4 if we're using MySQL 5.5.3+
088ad767 Fix continue / break warning under PHP 7.3
d1c7d5f5 Remove eval usages
2bd5e33d Update DB package to support PHP7.2
9fdcc074 CRM-21489 fix DatabaseObject code to retry when deadlock is met.
d26941f3 CRM-20414 (from CRM-14986) make DAO cope with DB dates (& datepicker dates) on update
20626692 CRM-20178 do not skip timestamps
a448be83 CRM-19930: Patch DB_DataObject::toArray() to sprintf only as needed
72d7f067 Fix mysqli_free and update DB_DataObject free to what is in their repo and port mollux change to DB.php for free
dc870cf1 CRM-17789 Add in insertId function
2722ad00 CRM-17789 - DB_common::raiseError() - Restore original signature
a7b4c90e Fixed forgotten parent contructor calls.
ddee1145 Made methods that are used statically static.
ab29b06c Fixed deprecated PHP 4 constructors + parent constructor calls.
e3b4406e CRM-18773
1c525140 CRM-17789 - DB_DataObject - PHP7 compatibility
b7a12ddc CRM-18093 More query debug info and a separate log file
182a6de1 CRM-18093 extend query time logging with string for grepping
579279f4 CRM-18093 Provide speed information on queries when CIVICRM_DEBUG_LOG_QUERY is on
ea1f2e6e CRM-16893 - Remove mysql_escape_string
4f06d1c6 PEAR DB - Remove unused drivers
256e5967     CRM-16431
520511d6 CRM-15522 make "Null" not evaluate as null if N is capitalized
ea5f80f0 Fix CRM-15212. Staticify PHP4 stuff. Ugh.
63001cb2 Update DataObject.php
283da611 CRM-14986 fix ongoing dao save problems on date fields
53da5fc6 handle update for blob datatype, CRM-14725
22477383 fixed DB DataObject to save blob field types
~~08e780cc Fix a typo in the mysql error codes (in upstream)~~

**Comment by seamuslee001** [comment]
@eileenmcnaughton i basically did a diff between what was in the _ORIGINAL_ folder originally and then re-applied them there. Also i worked through the civicrm-svn repo to find some original patches as well to see. I see at least i haven't re-applied https://github.com/civicrm/civicrm-packages/commit/ea1f2e6e89d076afdfe9f4e2363f7847410ac727 

I think i have re-applied all but this one i didn't https://github.com/civicrm/civicrm-packages/commit/a448be83d1322d35a1f045c4e7ca5fd7465dd96e as it seems the upstream has done a slightly different fix

**Comment by seamuslee001** [comment]
@eileenmcnaughton here are the actual differences as the PR is at the moment so we can figure out which patches have been added and which haven't (ignoring whitespace) https://gist.github.com/seamuslee001/4053b2657ca6fa7ae181f884176863bd

**Comment by seamuslee001** [comment]
~~4483923c CRM-20455 - DB_common::modifyQuery() - Optimize~~ (Not Applicable)
7c3733b9 Improve deadlock error handling - **Applied**
3df0ba15  CRM-20445 Add query dispatcher to allow query modification. - **Applied**
6ce43856 Change the connection and results charsets to utf8mb4 if we're using MySQL 5.5.3+ - **Applied**
088ad767 Fix continue / break warning under PHP 7.3 - **Applied**
~~d1c7d5f5 Remove eval usages ~~ Fixed upstream
~~2bd5e33d Update DB package to support PHP7.2~~ Not applicable to this PR
9fdcc074 CRM-21489 fix DatabaseObject code to retry when deadlock is met. - **Applied**
d26941f3 CRM-20414 (from CRM-14986) make DAO cope with DB dates (& datepicker dates) on update - **Applied**
20626692 CRM-20178 do not skip timestamps - **Applied**
~~a448be83 CRM-19930: Patch DB_DataObject::toArray() to sprintf only as needed~~ Not Needed as upstream appears to have done a similar fix https://github.com/civicrm/civicrm-packages/pull/278/files#diff-45a02a36cebf024e4fecc77cc0ad8e08R4128
~~72d7f067 Fix mysqli_free and update DB_DataObject free to what is in their repo and port mollux change to DB.php for free~~ (Fixed in upstream)
dc870cf1 CRM-17789 Add in insertId function - **Applied**
~~2722ad00 CRM-17789 - DB_common::raiseError() - Restore original signature~~ Not related to this file
~~a7b4c90e Fixed forgotten parent contructor calls.~~ Not related to this file
~~ddee1145 Made methods that are used statically static.~~ Not related to this file
ab29b06c Fixed deprecated PHP 4 constructors + parent constructor calls. - **Applied**
~~e3b4406e CRM-18773~~ Not needed as was removing some previous customisation
~~1c525140 CRM-17789 - DB_DataObject - PHP7 compatibility~~ Not needed any more as fixed in upstream
b7a12ddc CRM-18093 More query debug info and a separate log file - **Applied** 
182a6de1 CRM-18093 extend query time logging with string for grepping - **Applied**
579279f4 CRM-18093 Provide speed information on queries when CIVICRM_DEBUG_LOG_QUERY is on - **Applied**
~~ea1f2e6e CRM-16893 - Remove mysql_escape_string~~ Not related to this file
~~4f06d1c6 PEAR DB - Remove unused drivers~~ Not related to this file
256e5967     CRM-16431 - **Applied**
520511d6 CRM-15522 make "Null" not evaluate as null if N is capitalized - **Applied** in a different way to match upstream
ea5f80f0 Fix CRM-15212. Staticify PHP4 stuff. Ugh. - **Applied**
63001cb2 Update DataObject.php - **Applied**
283da611 CRM-14986 fix ongoing dao save problems on date fields - **Applied**
53da5fc6 handle update for blob datatype, CRM-14725 - **Applied**
22477383 fixed DB DataObject to save blob field types *How can this line even be reachable* - **Applied**
~~08e780cc Fix a typo in the mysql error codes (in upstream)~~ Not applicable to this file

**Comment by seamuslee001** [comment]
@eileenmcnaughton this is my analysis of those patches

**Comment by seamuslee001** [comment]
@eileenmcnaughton this is where i patched for Null https://github.com/civicrm/civicrm-packages/pull/278/files#diff-dcce25500e18eefca11d92b3728a04b9R4913 as upstream consolidated the is null handling into one function

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I concluded the only way to review this was to do it myself & compare the 2 - my version is here https://github.com/civicrm/civicrm-packages/pull/278 - it's almost the same except 
1) it's broken into patches
2) there are a few extra comments
3) that lastInsertID - I realised that it does nothing since no global is declared so it must not be called. I think it could only ever give an error if it is. It was for the purposes of php 7,0 support

**Comment by seamuslee001** [comment]
@eileenmcnaughton Looks fine to me to work on the other, Just a few comments on your PR

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yep - I think I addressed those - I realised that I had only been diffing one file! Hence I didn't resolve those

**Comment by eileenmcnaughton** [comment]
Here is what I have now

Eileens-MacBook-Pro:packages eileenmcnaughton$ git diff --ignore-space-at-eol -b -w --ignore-blank-lines seamus
diff --git a/DB/DataObject.php b/DB/DataObject.php
index 5e397933..6046a7e5 100644
--- a/DB/DataObject.php
+++ b/DB/DataObject.php
@@ -1165,6 +1165,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $rightq .= " NULL ";
                 continue;
             }
+
+            // CRM-14986 starts
             if (($v & DB_DATAOBJECT_DATE) || ($v & DB_DATAOBJECT_TIME) || $v & DB_DATAOBJECT_MYSQLTIMESTAMP) {
               if (strpos($this->$k, '-') !== FALSE) {
                 /*
@@ -1178,6 +1180,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $this->$k = CRM_Utils_Date::isoToMysql($this->$k);
               }
             }
+            // CRM-14986 ends
+
             // DATE is empty... on a col. that can be null..
:...skipping...
diff --git a/DB/DataObject.php b/DB/DataObject.php
index 5e397933..6046a7e5 100644
--- a/DB/DataObject.php
+++ b/DB/DataObject.php
@@ -1165,6 +1165,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $rightq .= " NULL ";
                 continue;
             }
+
+            // CRM-14986 starts
             if (($v & DB_DATAOBJECT_DATE) || ($v & DB_DATAOBJECT_TIME) || $v & DB_DATAOBJECT_MYSQLTIMESTAMP) {
               if (strpos($this->$k, '-') !== FALSE) {
                 /*
@@ -1178,6 +1180,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $this->$k = CRM_Utils_Date::isoToMysql($this->$k);
               }
             }
+            // CRM-14986 ends
+
             // DATE is empty... on a col. that can be null..
             // note: this may be usefull for time as well..
             if (!$this->$k &&
@@ -1200,6 +1204,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 continue;
             }
 
+            // CiviCRM hack CRM-14476: Extend CaseType API to return/save XML
:...skipping...
diff --git a/DB/DataObject.php b/DB/DataObject.php
index 5e397933..6046a7e5 100644
--- a/DB/DataObject.php
+++ b/DB/DataObject.php
@@ -1165,6 +1165,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $rightq .= " NULL ";
                 continue;
             }
+
+            // CRM-14986 starts
             if (($v & DB_DATAOBJECT_DATE) || ($v & DB_DATAOBJECT_TIME) || $v & DB_DATAOBJECT_MYSQLTIMESTAMP) {
               if (strpos($this->$k, '-') !== FALSE) {
                 /*
@@ -1178,6 +1180,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $this->$k = CRM_Utils_Date::isoToMysql($this->$k);
               }
             }
+            // CRM-14986 ends
+
             // DATE is empty... on a col. that can be null..
             // note: this may be usefull for time as well..
             if (!$this->$k &&
@@ -1200,6 +1204,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 continue;
             }
 
+            // CiviCRM hack CRM-14476: Extend CaseType API to return/save XML
+            // https://issues.civicrm.org/jira/browse/CRM-14476
             if ($v & DB_DATAOBJECT_TXT) {
                 $rightq .= $this->_quote((string) $this->$k ) . ' ';
                 continue;
@@ -1209,6 +1215,7 @@ class DB_DataObject extends DB_DataObject_Overload
                $rightq .= $this->_quote( $this->$k ) . ' ';
:...skipping...
diff --git a/DB/DataObject.php b/DB/DataObject.php
index 5e397933..6046a7e5 100644
--- a/DB/DataObject.php
+++ b/DB/DataObject.php
@@ -1165,6 +1165,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $rightq .= " NULL ";
                 continue;
             }
+
+            // CRM-14986 starts
             if (($v & DB_DATAOBJECT_DATE) || ($v & DB_DATAOBJECT_TIME) || $v & DB_DATAOBJECT_MYSQLTIMESTAMP) {
               if (strpos($this->$k, '-') !== FALSE) {
                 /*
@@ -1178,6 +1180,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $this->$k = CRM_Utils_Date::isoToMysql($this->$k);
               }
             }
+            // CRM-14986 ends
+
             // DATE is empty... on a col. that can be null..
             // note: this may be usefull for time as well..
             if (!$this->$k &&
@@ -1200,6 +1204,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 continue;
             }
 
+            // CiviCRM hack CRM-14476: Extend CaseType API to return/save XML
+            // https://issues.civicrm.org/jira/browse/CRM-14476
             if ($v & DB_DATAOBJECT_TXT) {
                 $rightq .= $this->_quote((string) $this->$k ) . ' ';
                 continue;
@@ -1209,6 +1215,7 @@ class DB_DataObject extends DB_DataObject_Overload
                $rightq .= $this->_quote( $this->$k ) . ' ';
                continue;
             }
+            // CRM-14476 hack ends
 
             if (is_numeric($this->$k)) {
                 $rightq .=" {$this->$k} ";
@@ -1445,6 +1452,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $settings .= "$kSql = NULL ";
                 continue;
             }
+
+            // CRM-14986 starts
             if (($v & DB_DATAOBJECT_DATE) || ($v & DB_DATAOBJECT_TIME) || $v & DB_DATAOBJECT_MYSQLTIMESTAMP) {
               if (strpos($this->$k, '-') !== FALSE) {
                /*
@@ -1458,6 +1467,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 $this->$k = CRM_Utils_Date::isoToMysql($this->$k);
               }
             }
+            // CRM-14986 ends
+
             // DATE is empty... on a col. that can be null..
             // note: this may be usefull for time as well..
             if (!$this->$k &&
@@ -1480,6 +1491,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 continue;
             }
 
+            // CiviCRM hack CRM-14476: Extend CaseType API to return/save XML
+            // https://issues.civicrm.org/jira/browse/CRM-14476
             if ($v & DB_DATAOBJECT_TXT) {
                 $settings .= "$kSql = " . $this->_quote((string) $this->$k ) . ' ';
                 continue;
@@ -1489,6 +1502,7 @@ class DB_DataObject extends DB_DataObject_Overload
               $settings .= "$kSql = " . $this->_quote($this->$k ) . ' ';
               continue;
             }
+            // CRM-14725 ends
 
             if (is_numeric($this->$k)) {
                 $settings .= "$kSql = {$this->$k} ";
@@ -2557,7 +2571,7 @@ class DB_DataObject extends DB_DataObject_Overload
 
         }
 
-        // change the connection and results charsets to UTF-8 if we're using MySQL 4.1+
+        // Change the connection and results charsets to utf8mb4 if we're using MySQL 5.5.3+
         $civicrmConfig = CRM_Core_Config::singleton();
         $this->query("/*!40101 SET NAMES utf8 */");
         $this->query("/*!50503 SET NAMES utf8mb4 */");
@@ -2607,7 +2621,7 @@ class DB_DataObject extends DB_DataObject_Overload
         global $_DB_DATAOBJECT;
         $this->_connect();
 
-        // Logging the query first makes sure it gets logged even if it fails.
+        // CRM-18093 Logging the query first makes sure it gets logged even if it fails.
         CRM_Core_Error::debug_query($string);
 
         $DB = $_DB_DATAOBJECT['CONNECTIONS'][$this->_database_dsn_md5];
@@ -2734,15 +2747,17 @@ class DB_DataObject extends DB_DataObject_Overload
             return $this->raiseError($result);
         }
 
-        // Strip any prepended comments
+        // CRM-18093 starts.
+        // CRM-20445 starts Strip any prepended comments
         $queryString = (substr($string, 0, 2) === '/*') ? substr($string, strpos($string, '*/') + 2) : $string;
         $action = strtolower(substr(trim($queryString),0,6));
+        // CRM-20445 ends
 
         if (!empty($_DB_DATAOBJECT['CONFIG']['debug']) || defined('CIVICRM_DEBUG_LOG_QUERY')) {
           $timeTaken = sprintf("%0.6f", microtime(TRUE) - $time);
           $alertLevel = $this->getAlertLevel($timeTaken);
           $message = "$alertLevel QUERY DONE IN $timeTaken  seconds.";
-            if (in_array($action, array('insert', 'update', 'delete')) && $_DB_driver == 'DB') {
+          if (in_array($action, ['insert', 'update', 'delete']) && $_DB_driver === 'DB') {
             $message .= " " . $DB->affectedRows() . " row(s)s subject to $action action";
           }
           elseif (is_a($result, 'DB_result') && method_exists($result, 'numrows')) {
@@ -2761,6 +2776,8 @@ class DB_DataObject extends DB_DataObject_Overload
             $this->debug($message, 'query', 1);
           }
         }
+      // CRM-18093 ends.
+
         switch ($action) {
             case 'insert':
             case 'update':
@@ -4744,9 +4760,12 @@ class DB_DataObject extends DB_DataObject_Overload
      * @param   int     $v  level
      * @access  public
      * @return  none
+     *
+     * CRM-15212 fix visibility.
      */
     public static function debugLevel($v = null)
     {
+        // CRM-15212. ends
         global $_DB_DATAOBJECT;
         if (empty($_DB_DATAOBJECT['CONFIG'])) {
             DB_DataObject::_loadConfig();
@@ -4912,7 +4931,8 @@ class DB_DataObject extends DB_DataObject_Overload
                 && strtolower($options['disable_null_strings'] === 'full');
 
         // CRM-15522 Ensure that Last name of Null is validly stored.
-        if ( $null_strings && $isset  && is_string($value)  && (strtolower($value) === 'null' && $value !== 'Null') ) {
+        if ( $null_strings && $isset  && is_string($value)  && (strtolower($value) === 'null')  && $value !== 'Null') {
+        // CRM-15522 ends
             return true;
         }
 
@@ -5010,6 +5030,8 @@ class DB_DataObject extends DB_DataObject_Overload
    * @param float $timeTaken
    *
    * @return string
+   *
+   * function only needed for CRM-18093.
    */
   public function getAlertLevel($timeTaken) {
     if ($timeTaken >= 20) {
@@ -5027,11 +5049,6 @@ class DB_DataObject extends DB_DataObject_Overload
     return '';
   }
 
-    public function lastInsertId() {
-        $DB = $_DB_DATAOBJECT['CONNECTIONS'][$this->_database_dsn_md5];
-        return $DB->lastInsertId();
-    }
-
 }
 // technially 4.3.2RC1 was broken!!
 // looks like 4.3.3 may have problems too....
diff --git a/DB/common.php b/DB/common.php
index 1b819743..92a8143b 100644
--- a/DB/common.php
+++ b/DB/common.php
@@ -1147,6 +1147,7 @@ class DB_common extends PEAR
      */
     function modifyQuery($query)
     {
+        // CRM-20445 Add query dispatcher to allow query modification.
         // This section of code may run hundreds or thousands of times in a given request.
         // Consequently, it is micro-optimized to use single lookup in typical case.
         if (!isset(Civi::$statics['db_common_dispatcher'])) {
@@ -1160,6 +1161,7 @@ class DB_common extends PEAR
 
         $e = new \Civi\Core\Event\QueryEvent($query);
         Civi::$statics['db_common_dispatcher']->dispatch('civi.db.query', $e);
+        // CRM-20445 ends.
         return $e->query;
     }

**Comment by eileenmcnaughton** [comment]
So only one functional change...

**Comment by seamuslee001** [comment]
Yeh that might need to go back the lastInsertId i think there might be transaction tests that rely on it i think

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it doesn't make any sense though - doesn't $_DB_DATAOBJECT need to be declared as a global for it to be used as a global?

**Comment by seamuslee001** [comment]
closing in favour of #278

**Pull request closed without merging**
