### PR TITLE
CRM-20243 Update jquery in kcfinder

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten

---

 * [CRM-20243](https://issues.civicrm.org/jira/browse/CRM-20243)

### CODE REVIEW

**Comment by totten** [comment]
Did you determine if this file was actually in use?

**Comment by seamuslee001** [comment]
So i think this file is used but its been compiled together already into a cache version but upstream doesn't seem to have changed either

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by Akhond-Zada** [comment]
Hello  all my credit  cards  are stolen

**Comment by seamuslee001** [comment]
closing as dealt with separately

**Pull request closed without merging**
