### PR TITLE
CRM-18773

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-18773](https://issues.civicrm.org/jira/browse/CRM-18773)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@xurizaemon

**Comment by xurizaemon** [comment]
See CRM-18773 before merging.

**Comment by eileenmcnaughton** [comment]
4.6 PR still required?

**Comment by seamuslee001** [comment]
I think so

**Comment by eileenmcnaughton** [comment]
found it

**Pull request merged**
