### PR TITLE
Remove unsupported and unused package DB_Table

### PR DESCRIPTION
**Pull request by seamuslee001**
I did a grep on the DB_Table class and cannot see it being used anywhere

ping @totten @colemanw @eileenmcnaughton according to PEAR https://pear.php.net/package/DB_Table/ it is not maintained at all

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
We've just cut the rc so this is a good time to merge - the tests pass & I couldn't find any references outside of the package so merging

**Comment by totten** [comment]
🎉

**Pull request merged**
