### PR TITLE
[REF] dev/drupal#169 Replace other usages of session_id with CRM_Core…

### PR DESCRIPTION
**Pull request by seamuslee001**
…_Config::singleton()->userSystem->getSessionId

ping @demeritcowboy @MegaphoneJon

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
This is a little difficult to test because kcfinder doesn't work properly in drupal 8 (error 404's). Codewise it looks fine except again it probably doesn't need to be against 5.44. And it seems wrong if a site is letting anonymous browse and upload files (my point being towards not needing a backport).

**Comment by seamuslee001** [comment]
ok @demeritcowboy I have shifted this to master now

**Comment by demeritcowboy** [comment]
Thanks.

**Comment by demeritcowboy** [comment]
I've added https://github.com/civicrm/civicrm-packages/pull/338 to add the backslash.

**Pull request merged**
