### PR TITLE
[REF] Remove DB Package as it is now deployed using composer

### PR DESCRIPTION
**Pull request by seamuslee001**
This depends on https://github.com/civicrm/civicrm-core/pull/18027

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@demeritcowboy @eileenmcnaughton big green tick now

**Comment by demeritcowboy** [comment]
Cool. One thing to note is that for people who manage git installs, the order you do things will matter here. You need to pull packages, then run composer install on the main tree, otherwise the include_path doesn't include vendor/pear/db.

UI seems ok. I tried some different entry points like cron/cv/cli and looks good. Only tried drupal 7.

**Comment by eileenmcnaughton** [comment]
OK as discussed - we wanted to merge this straight after the rc is cut for max pre-release time - so that happened

**Pull request merged**
