### PR TITLE
Upgrade Mime_mail to fix issues with PHP7.2

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @totten @monishdeb

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton this now includes an upgrade to the latest version of Mail_Mime

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
This PR picks the latest changes from ```Mail_mime``` and ```Mail_mimeDecodeFrom``` package and from code pov after I crosschecked what are the changes bring bought up during upgrade and how it will impact the Civi codebase, here's my report on code POV:
1. Remove underscores from protected method and variables - [upstream commit](https://github.com/pear/Mail_Mime/commit/092b996e6ecff85fe9c8c6250de4137e18d61bfe)
 Except for the ```$mime->_headers``` Civi doesn't use any of the function/variables directly as I greped the universe. And @seamuslee001 has already submitted a PR https://github.com/civicrm/civicrm-core/pull/12169 in this regard.
Without this fix it shows a placeholder as in:
screen shot 2018-05-22 at 12 58 58 pm

2. Drop PHP4 and add PHP7 support - [upstream commit](https://github.com/pear/Mail_Mime/commit/1b6fa2dece33e8de78a32babc6b029e8de2ebee9) 
  All the changes are safe and I have tested on php7.2 instance
3. Added methods for creating text/calendar messages - [upstream commit](https://github.com/pear/Mail_Mime/commit/2d0c85bbdad83dc774ffd2d40ffa5093895a84a7)
That's a nice feature for text/calendar message and can be utilised in core.
4. Mail_mimePart file has similar changes as of 1 and 2
5. Mail_mimeDecode changes makes sense however I didn't found any upstream commits to compare with. So I had to rely on UI test to check any unintended behaviour, although this package is being internally used by Mail_mime and as per my tests on php7.2 UI end and doesn't raise any concern from UI end.

Except the for the minor issue for which I there is already a core PR I didn't encountered any issue in php7.2




* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Searched in [test build](http://pkg-205-1lejr.test-ubu1204-5.civicrm.org) and on local and able to send mail
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Comment by monishdeb** [comment]
[Test failure](https://test.civicrm.org/job/CiviCRM-Packages-PR/72/testReport/) will be fixed by https://github.com/civicrm/civicrm-core/pull/12169

**Pull request merged**
